// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ConnectedSession is the predicate function for connectedsession builders.
type ConnectedSession func(*sql.Selector)

// HusSession is the predicate function for hussession builders.
type HusSession func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
