// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hus-auth/ent/connectedsessions"
	"hus-auth/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConnectedSessionsQuery is the builder for querying ConnectedSessions entities.
type ConnectedSessionsQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.ConnectedSessions
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ConnectedSessionsQuery builder.
func (csq *ConnectedSessionsQuery) Where(ps ...predicate.ConnectedSessions) *ConnectedSessionsQuery {
	csq.predicates = append(csq.predicates, ps...)
	return csq
}

// Limit the number of records to be returned by this query.
func (csq *ConnectedSessionsQuery) Limit(limit int) *ConnectedSessionsQuery {
	csq.ctx.Limit = &limit
	return csq
}

// Offset to start from.
func (csq *ConnectedSessionsQuery) Offset(offset int) *ConnectedSessionsQuery {
	csq.ctx.Offset = &offset
	return csq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (csq *ConnectedSessionsQuery) Unique(unique bool) *ConnectedSessionsQuery {
	csq.ctx.Unique = &unique
	return csq
}

// Order specifies how the records should be ordered.
func (csq *ConnectedSessionsQuery) Order(o ...OrderFunc) *ConnectedSessionsQuery {
	csq.order = append(csq.order, o...)
	return csq
}

// First returns the first ConnectedSessions entity from the query.
// Returns a *NotFoundError when no ConnectedSessions was found.
func (csq *ConnectedSessionsQuery) First(ctx context.Context) (*ConnectedSessions, error) {
	nodes, err := csq.Limit(1).All(setContextOp(ctx, csq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{connectedsessions.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (csq *ConnectedSessionsQuery) FirstX(ctx context.Context) *ConnectedSessions {
	node, err := csq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ConnectedSessions ID from the query.
// Returns a *NotFoundError when no ConnectedSessions ID was found.
func (csq *ConnectedSessionsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(1).IDs(setContextOp(ctx, csq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{connectedsessions.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (csq *ConnectedSessionsQuery) FirstIDX(ctx context.Context) int {
	id, err := csq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ConnectedSessions entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ConnectedSessions entity is found.
// Returns a *NotFoundError when no ConnectedSessions entities are found.
func (csq *ConnectedSessionsQuery) Only(ctx context.Context) (*ConnectedSessions, error) {
	nodes, err := csq.Limit(2).All(setContextOp(ctx, csq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{connectedsessions.Label}
	default:
		return nil, &NotSingularError{connectedsessions.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (csq *ConnectedSessionsQuery) OnlyX(ctx context.Context) *ConnectedSessions {
	node, err := csq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ConnectedSessions ID in the query.
// Returns a *NotSingularError when more than one ConnectedSessions ID is found.
// Returns a *NotFoundError when no entities are found.
func (csq *ConnectedSessionsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(2).IDs(setContextOp(ctx, csq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{connectedsessions.Label}
	default:
		err = &NotSingularError{connectedsessions.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (csq *ConnectedSessionsQuery) OnlyIDX(ctx context.Context) int {
	id, err := csq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ConnectedSessionsSlice.
func (csq *ConnectedSessionsQuery) All(ctx context.Context) ([]*ConnectedSessions, error) {
	ctx = setContextOp(ctx, csq.ctx, "All")
	if err := csq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ConnectedSessions, *ConnectedSessionsQuery]()
	return withInterceptors[[]*ConnectedSessions](ctx, csq, qr, csq.inters)
}

// AllX is like All, but panics if an error occurs.
func (csq *ConnectedSessionsQuery) AllX(ctx context.Context) []*ConnectedSessions {
	nodes, err := csq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ConnectedSessions IDs.
func (csq *ConnectedSessionsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if csq.ctx.Unique == nil && csq.path != nil {
		csq.Unique(true)
	}
	ctx = setContextOp(ctx, csq.ctx, "IDs")
	if err = csq.Select(connectedsessions.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (csq *ConnectedSessionsQuery) IDsX(ctx context.Context) []int {
	ids, err := csq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (csq *ConnectedSessionsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, csq.ctx, "Count")
	if err := csq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, csq, querierCount[*ConnectedSessionsQuery](), csq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (csq *ConnectedSessionsQuery) CountX(ctx context.Context) int {
	count, err := csq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (csq *ConnectedSessionsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, csq.ctx, "Exist")
	switch _, err := csq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (csq *ConnectedSessionsQuery) ExistX(ctx context.Context) bool {
	exist, err := csq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ConnectedSessionsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (csq *ConnectedSessionsQuery) Clone() *ConnectedSessionsQuery {
	if csq == nil {
		return nil
	}
	return &ConnectedSessionsQuery{
		config:     csq.config,
		ctx:        csq.ctx.Clone(),
		order:      append([]OrderFunc{}, csq.order...),
		inters:     append([]Interceptor{}, csq.inters...),
		predicates: append([]predicate.ConnectedSessions{}, csq.predicates...),
		// clone intermediate query.
		sql:  csq.sql.Clone(),
		path: csq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Hsid uuid.UUID `json:"hsid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ConnectedSessions.Query().
//		GroupBy(connectedsessions.FieldHsid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (csq *ConnectedSessionsQuery) GroupBy(field string, fields ...string) *ConnectedSessionsGroupBy {
	csq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ConnectedSessionsGroupBy{build: csq}
	grbuild.flds = &csq.ctx.Fields
	grbuild.label = connectedsessions.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Hsid uuid.UUID `json:"hsid,omitempty"`
//	}
//
//	client.ConnectedSessions.Query().
//		Select(connectedsessions.FieldHsid).
//		Scan(ctx, &v)
func (csq *ConnectedSessionsQuery) Select(fields ...string) *ConnectedSessionsSelect {
	csq.ctx.Fields = append(csq.ctx.Fields, fields...)
	sbuild := &ConnectedSessionsSelect{ConnectedSessionsQuery: csq}
	sbuild.label = connectedsessions.Label
	sbuild.flds, sbuild.scan = &csq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ConnectedSessionsSelect configured with the given aggregations.
func (csq *ConnectedSessionsQuery) Aggregate(fns ...AggregateFunc) *ConnectedSessionsSelect {
	return csq.Select().Aggregate(fns...)
}

func (csq *ConnectedSessionsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range csq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, csq); err != nil {
				return err
			}
		}
	}
	for _, f := range csq.ctx.Fields {
		if !connectedsessions.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if csq.path != nil {
		prev, err := csq.path(ctx)
		if err != nil {
			return err
		}
		csq.sql = prev
	}
	return nil
}

func (csq *ConnectedSessionsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ConnectedSessions, error) {
	var (
		nodes = []*ConnectedSessions{}
		_spec = csq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ConnectedSessions).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ConnectedSessions{config: csq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, csq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (csq *ConnectedSessionsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := csq.querySpec()
	_spec.Node.Columns = csq.ctx.Fields
	if len(csq.ctx.Fields) > 0 {
		_spec.Unique = csq.ctx.Unique != nil && *csq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, csq.driver, _spec)
}

func (csq *ConnectedSessionsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(connectedsessions.Table, connectedsessions.Columns, sqlgraph.NewFieldSpec(connectedsessions.FieldID, field.TypeInt))
	_spec.From = csq.sql
	if unique := csq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if csq.path != nil {
		_spec.Unique = true
	}
	if fields := csq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, connectedsessions.FieldID)
		for i := range fields {
			if fields[i] != connectedsessions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := csq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := csq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := csq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := csq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (csq *ConnectedSessionsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(csq.driver.Dialect())
	t1 := builder.Table(connectedsessions.Table)
	columns := csq.ctx.Fields
	if len(columns) == 0 {
		columns = connectedsessions.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if csq.sql != nil {
		selector = csq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if csq.ctx.Unique != nil && *csq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range csq.predicates {
		p(selector)
	}
	for _, p := range csq.order {
		p(selector)
	}
	if offset := csq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := csq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ConnectedSessionsGroupBy is the group-by builder for ConnectedSessions entities.
type ConnectedSessionsGroupBy struct {
	selector
	build *ConnectedSessionsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (csgb *ConnectedSessionsGroupBy) Aggregate(fns ...AggregateFunc) *ConnectedSessionsGroupBy {
	csgb.fns = append(csgb.fns, fns...)
	return csgb
}

// Scan applies the selector query and scans the result into the given value.
func (csgb *ConnectedSessionsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, csgb.build.ctx, "GroupBy")
	if err := csgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConnectedSessionsQuery, *ConnectedSessionsGroupBy](ctx, csgb.build, csgb, csgb.build.inters, v)
}

func (csgb *ConnectedSessionsGroupBy) sqlScan(ctx context.Context, root *ConnectedSessionsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(csgb.fns))
	for _, fn := range csgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*csgb.flds)+len(csgb.fns))
		for _, f := range *csgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*csgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := csgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ConnectedSessionsSelect is the builder for selecting fields of ConnectedSessions entities.
type ConnectedSessionsSelect struct {
	*ConnectedSessionsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (css *ConnectedSessionsSelect) Aggregate(fns ...AggregateFunc) *ConnectedSessionsSelect {
	css.fns = append(css.fns, fns...)
	return css
}

// Scan applies the selector query and scans the result into the given value.
func (css *ConnectedSessionsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, css.ctx, "Select")
	if err := css.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConnectedSessionsQuery, *ConnectedSessionsSelect](ctx, css.ConnectedSessionsQuery, css, css.inters, v)
}

func (css *ConnectedSessionsSelect) sqlScan(ctx context.Context, root *ConnectedSessionsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(css.fns))
	for _, fn := range css.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*css.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := css.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
