// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hus-auth/ent/connectedsession"
	"hus-auth/ent/hussession"
	"hus-auth/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ConnectedSessionQuery is the builder for querying ConnectedSession entities.
type ConnectedSessionQuery struct {
	config
	ctx            *QueryContext
	order          []OrderFunc
	inters         []Interceptor
	predicates     []predicate.ConnectedSession
	withHusSession *HusSessionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ConnectedSessionQuery builder.
func (csq *ConnectedSessionQuery) Where(ps ...predicate.ConnectedSession) *ConnectedSessionQuery {
	csq.predicates = append(csq.predicates, ps...)
	return csq
}

// Limit the number of records to be returned by this query.
func (csq *ConnectedSessionQuery) Limit(limit int) *ConnectedSessionQuery {
	csq.ctx.Limit = &limit
	return csq
}

// Offset to start from.
func (csq *ConnectedSessionQuery) Offset(offset int) *ConnectedSessionQuery {
	csq.ctx.Offset = &offset
	return csq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (csq *ConnectedSessionQuery) Unique(unique bool) *ConnectedSessionQuery {
	csq.ctx.Unique = &unique
	return csq
}

// Order specifies how the records should be ordered.
func (csq *ConnectedSessionQuery) Order(o ...OrderFunc) *ConnectedSessionQuery {
	csq.order = append(csq.order, o...)
	return csq
}

// QueryHusSession chains the current query on the "hus_session" edge.
func (csq *ConnectedSessionQuery) QueryHusSession() *HusSessionQuery {
	query := (&HusSessionClient{config: csq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := csq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := csq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(connectedsession.Table, connectedsession.FieldID, selector),
			sqlgraph.To(hussession.Table, hussession.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, connectedsession.HusSessionTable, connectedsession.HusSessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(csq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ConnectedSession entity from the query.
// Returns a *NotFoundError when no ConnectedSession was found.
func (csq *ConnectedSessionQuery) First(ctx context.Context) (*ConnectedSession, error) {
	nodes, err := csq.Limit(1).All(setContextOp(ctx, csq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{connectedsession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (csq *ConnectedSessionQuery) FirstX(ctx context.Context) *ConnectedSession {
	node, err := csq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ConnectedSession ID from the query.
// Returns a *NotFoundError when no ConnectedSession ID was found.
func (csq *ConnectedSessionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(1).IDs(setContextOp(ctx, csq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{connectedsession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (csq *ConnectedSessionQuery) FirstIDX(ctx context.Context) int {
	id, err := csq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ConnectedSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ConnectedSession entity is found.
// Returns a *NotFoundError when no ConnectedSession entities are found.
func (csq *ConnectedSessionQuery) Only(ctx context.Context) (*ConnectedSession, error) {
	nodes, err := csq.Limit(2).All(setContextOp(ctx, csq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{connectedsession.Label}
	default:
		return nil, &NotSingularError{connectedsession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (csq *ConnectedSessionQuery) OnlyX(ctx context.Context) *ConnectedSession {
	node, err := csq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ConnectedSession ID in the query.
// Returns a *NotSingularError when more than one ConnectedSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (csq *ConnectedSessionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(2).IDs(setContextOp(ctx, csq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{connectedsession.Label}
	default:
		err = &NotSingularError{connectedsession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (csq *ConnectedSessionQuery) OnlyIDX(ctx context.Context) int {
	id, err := csq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ConnectedSessions.
func (csq *ConnectedSessionQuery) All(ctx context.Context) ([]*ConnectedSession, error) {
	ctx = setContextOp(ctx, csq.ctx, "All")
	if err := csq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ConnectedSession, *ConnectedSessionQuery]()
	return withInterceptors[[]*ConnectedSession](ctx, csq, qr, csq.inters)
}

// AllX is like All, but panics if an error occurs.
func (csq *ConnectedSessionQuery) AllX(ctx context.Context) []*ConnectedSession {
	nodes, err := csq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ConnectedSession IDs.
func (csq *ConnectedSessionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if csq.ctx.Unique == nil && csq.path != nil {
		csq.Unique(true)
	}
	ctx = setContextOp(ctx, csq.ctx, "IDs")
	if err = csq.Select(connectedsession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (csq *ConnectedSessionQuery) IDsX(ctx context.Context) []int {
	ids, err := csq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (csq *ConnectedSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, csq.ctx, "Count")
	if err := csq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, csq, querierCount[*ConnectedSessionQuery](), csq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (csq *ConnectedSessionQuery) CountX(ctx context.Context) int {
	count, err := csq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (csq *ConnectedSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, csq.ctx, "Exist")
	switch _, err := csq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (csq *ConnectedSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := csq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ConnectedSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (csq *ConnectedSessionQuery) Clone() *ConnectedSessionQuery {
	if csq == nil {
		return nil
	}
	return &ConnectedSessionQuery{
		config:         csq.config,
		ctx:            csq.ctx.Clone(),
		order:          append([]OrderFunc{}, csq.order...),
		inters:         append([]Interceptor{}, csq.inters...),
		predicates:     append([]predicate.ConnectedSession{}, csq.predicates...),
		withHusSession: csq.withHusSession.Clone(),
		// clone intermediate query.
		sql:  csq.sql.Clone(),
		path: csq.path,
	}
}

// WithHusSession tells the query-builder to eager-load the nodes that are connected to
// the "hus_session" edge. The optional arguments are used to configure the query builder of the edge.
func (csq *ConnectedSessionQuery) WithHusSession(opts ...func(*HusSessionQuery)) *ConnectedSessionQuery {
	query := (&HusSessionClient{config: csq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	csq.withHusSession = query
	return csq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Hsid uuid.UUID `json:"hsid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ConnectedSession.Query().
//		GroupBy(connectedsession.FieldHsid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (csq *ConnectedSessionQuery) GroupBy(field string, fields ...string) *ConnectedSessionGroupBy {
	csq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ConnectedSessionGroupBy{build: csq}
	grbuild.flds = &csq.ctx.Fields
	grbuild.label = connectedsession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Hsid uuid.UUID `json:"hsid,omitempty"`
//	}
//
//	client.ConnectedSession.Query().
//		Select(connectedsession.FieldHsid).
//		Scan(ctx, &v)
func (csq *ConnectedSessionQuery) Select(fields ...string) *ConnectedSessionSelect {
	csq.ctx.Fields = append(csq.ctx.Fields, fields...)
	sbuild := &ConnectedSessionSelect{ConnectedSessionQuery: csq}
	sbuild.label = connectedsession.Label
	sbuild.flds, sbuild.scan = &csq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ConnectedSessionSelect configured with the given aggregations.
func (csq *ConnectedSessionQuery) Aggregate(fns ...AggregateFunc) *ConnectedSessionSelect {
	return csq.Select().Aggregate(fns...)
}

func (csq *ConnectedSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range csq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, csq); err != nil {
				return err
			}
		}
	}
	for _, f := range csq.ctx.Fields {
		if !connectedsession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if csq.path != nil {
		prev, err := csq.path(ctx)
		if err != nil {
			return err
		}
		csq.sql = prev
	}
	return nil
}

func (csq *ConnectedSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ConnectedSession, error) {
	var (
		nodes       = []*ConnectedSession{}
		_spec       = csq.querySpec()
		loadedTypes = [1]bool{
			csq.withHusSession != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ConnectedSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ConnectedSession{config: csq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, csq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := csq.withHusSession; query != nil {
		if err := csq.loadHusSession(ctx, query, nodes, nil,
			func(n *ConnectedSession, e *HusSession) { n.Edges.HusSession = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (csq *ConnectedSessionQuery) loadHusSession(ctx context.Context, query *HusSessionQuery, nodes []*ConnectedSession, init func(*ConnectedSession), assign func(*ConnectedSession, *HusSession)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ConnectedSession)
	for i := range nodes {
		fk := nodes[i].Hsid
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(hussession.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "hsid" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (csq *ConnectedSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := csq.querySpec()
	_spec.Node.Columns = csq.ctx.Fields
	if len(csq.ctx.Fields) > 0 {
		_spec.Unique = csq.ctx.Unique != nil && *csq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, csq.driver, _spec)
}

func (csq *ConnectedSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(connectedsession.Table, connectedsession.Columns, sqlgraph.NewFieldSpec(connectedsession.FieldID, field.TypeInt))
	_spec.From = csq.sql
	if unique := csq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if csq.path != nil {
		_spec.Unique = true
	}
	if fields := csq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, connectedsession.FieldID)
		for i := range fields {
			if fields[i] != connectedsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := csq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := csq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := csq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := csq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (csq *ConnectedSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(csq.driver.Dialect())
	t1 := builder.Table(connectedsession.Table)
	columns := csq.ctx.Fields
	if len(columns) == 0 {
		columns = connectedsession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if csq.sql != nil {
		selector = csq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if csq.ctx.Unique != nil && *csq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range csq.predicates {
		p(selector)
	}
	for _, p := range csq.order {
		p(selector)
	}
	if offset := csq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := csq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ConnectedSessionGroupBy is the group-by builder for ConnectedSession entities.
type ConnectedSessionGroupBy struct {
	selector
	build *ConnectedSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (csgb *ConnectedSessionGroupBy) Aggregate(fns ...AggregateFunc) *ConnectedSessionGroupBy {
	csgb.fns = append(csgb.fns, fns...)
	return csgb
}

// Scan applies the selector query and scans the result into the given value.
func (csgb *ConnectedSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, csgb.build.ctx, "GroupBy")
	if err := csgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConnectedSessionQuery, *ConnectedSessionGroupBy](ctx, csgb.build, csgb, csgb.build.inters, v)
}

func (csgb *ConnectedSessionGroupBy) sqlScan(ctx context.Context, root *ConnectedSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(csgb.fns))
	for _, fn := range csgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*csgb.flds)+len(csgb.fns))
		for _, f := range *csgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*csgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := csgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ConnectedSessionSelect is the builder for selecting fields of ConnectedSession entities.
type ConnectedSessionSelect struct {
	*ConnectedSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (css *ConnectedSessionSelect) Aggregate(fns ...AggregateFunc) *ConnectedSessionSelect {
	css.fns = append(css.fns, fns...)
	return css
}

// Scan applies the selector query and scans the result into the given value.
func (css *ConnectedSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, css.ctx, "Select")
	if err := css.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConnectedSessionQuery, *ConnectedSessionSelect](ctx, css.ConnectedSessionQuery, css, css.inters, v)
}

func (css *ConnectedSessionSelect) sqlScan(ctx context.Context, root *ConnectedSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(css.fns))
	for _, fn := range css.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*css.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := css.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
