// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hus-auth/ent/hussession"
	"hus-auth/ent/predicate"
	"hus-auth/ent/user"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// HusSessionQuery is the builder for querying HusSession entities.
type HusSessionQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.HusSession
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HusSessionQuery builder.
func (hsq *HusSessionQuery) Where(ps ...predicate.HusSession) *HusSessionQuery {
	hsq.predicates = append(hsq.predicates, ps...)
	return hsq
}

// Limit the number of records to be returned by this query.
func (hsq *HusSessionQuery) Limit(limit int) *HusSessionQuery {
	hsq.ctx.Limit = &limit
	return hsq
}

// Offset to start from.
func (hsq *HusSessionQuery) Offset(offset int) *HusSessionQuery {
	hsq.ctx.Offset = &offset
	return hsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hsq *HusSessionQuery) Unique(unique bool) *HusSessionQuery {
	hsq.ctx.Unique = &unique
	return hsq
}

// Order specifies how the records should be ordered.
func (hsq *HusSessionQuery) Order(o ...OrderFunc) *HusSessionQuery {
	hsq.order = append(hsq.order, o...)
	return hsq
}

// QueryUser chains the current query on the "user" edge.
func (hsq *HusSessionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: hsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hussession.Table, hussession.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, hussession.UserTable, hussession.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(hsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HusSession entity from the query.
// Returns a *NotFoundError when no HusSession was found.
func (hsq *HusSessionQuery) First(ctx context.Context) (*HusSession, error) {
	nodes, err := hsq.Limit(1).All(setContextOp(ctx, hsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hussession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hsq *HusSessionQuery) FirstX(ctx context.Context) *HusSession {
	node, err := hsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HusSession ID from the query.
// Returns a *NotFoundError when no HusSession ID was found.
func (hsq *HusSessionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = hsq.Limit(1).IDs(setContextOp(ctx, hsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hussession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hsq *HusSessionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := hsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HusSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HusSession entity is found.
// Returns a *NotFoundError when no HusSession entities are found.
func (hsq *HusSessionQuery) Only(ctx context.Context) (*HusSession, error) {
	nodes, err := hsq.Limit(2).All(setContextOp(ctx, hsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hussession.Label}
	default:
		return nil, &NotSingularError{hussession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hsq *HusSessionQuery) OnlyX(ctx context.Context) *HusSession {
	node, err := hsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HusSession ID in the query.
// Returns a *NotSingularError when more than one HusSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (hsq *HusSessionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = hsq.Limit(2).IDs(setContextOp(ctx, hsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hussession.Label}
	default:
		err = &NotSingularError{hussession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hsq *HusSessionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := hsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HusSessions.
func (hsq *HusSessionQuery) All(ctx context.Context) ([]*HusSession, error) {
	ctx = setContextOp(ctx, hsq.ctx, "All")
	if err := hsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HusSession, *HusSessionQuery]()
	return withInterceptors[[]*HusSession](ctx, hsq, qr, hsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hsq *HusSessionQuery) AllX(ctx context.Context) []*HusSession {
	nodes, err := hsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HusSession IDs.
func (hsq *HusSessionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if hsq.ctx.Unique == nil && hsq.path != nil {
		hsq.Unique(true)
	}
	ctx = setContextOp(ctx, hsq.ctx, "IDs")
	if err = hsq.Select(hussession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hsq *HusSessionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := hsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hsq *HusSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hsq.ctx, "Count")
	if err := hsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hsq, querierCount[*HusSessionQuery](), hsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hsq *HusSessionQuery) CountX(ctx context.Context) int {
	count, err := hsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hsq *HusSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hsq.ctx, "Exist")
	switch _, err := hsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hsq *HusSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := hsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HusSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hsq *HusSessionQuery) Clone() *HusSessionQuery {
	if hsq == nil {
		return nil
	}
	return &HusSessionQuery{
		config:     hsq.config,
		ctx:        hsq.ctx.Clone(),
		order:      append([]OrderFunc{}, hsq.order...),
		inters:     append([]Interceptor{}, hsq.inters...),
		predicates: append([]predicate.HusSession{}, hsq.predicates...),
		withUser:   hsq.withUser.Clone(),
		// clone intermediate query.
		sql:  hsq.sql.Clone(),
		path: hsq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (hsq *HusSessionQuery) WithUser(opts ...func(*UserQuery)) *HusSessionQuery {
	query := (&UserClient{config: hsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hsq.withUser = query
	return hsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Tid uuid.UUID `json:"tid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HusSession.Query().
//		GroupBy(hussession.FieldTid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hsq *HusSessionQuery) GroupBy(field string, fields ...string) *HusSessionGroupBy {
	hsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HusSessionGroupBy{build: hsq}
	grbuild.flds = &hsq.ctx.Fields
	grbuild.label = hussession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Tid uuid.UUID `json:"tid,omitempty"`
//	}
//
//	client.HusSession.Query().
//		Select(hussession.FieldTid).
//		Scan(ctx, &v)
func (hsq *HusSessionQuery) Select(fields ...string) *HusSessionSelect {
	hsq.ctx.Fields = append(hsq.ctx.Fields, fields...)
	sbuild := &HusSessionSelect{HusSessionQuery: hsq}
	sbuild.label = hussession.Label
	sbuild.flds, sbuild.scan = &hsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HusSessionSelect configured with the given aggregations.
func (hsq *HusSessionQuery) Aggregate(fns ...AggregateFunc) *HusSessionSelect {
	return hsq.Select().Aggregate(fns...)
}

func (hsq *HusSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hsq); err != nil {
				return err
			}
		}
	}
	for _, f := range hsq.ctx.Fields {
		if !hussession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hsq.path != nil {
		prev, err := hsq.path(ctx)
		if err != nil {
			return err
		}
		hsq.sql = prev
	}
	return nil
}

func (hsq *HusSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HusSession, error) {
	var (
		nodes       = []*HusSession{}
		_spec       = hsq.querySpec()
		loadedTypes = [1]bool{
			hsq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HusSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HusSession{config: hsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := hsq.withUser; query != nil {
		if err := hsq.loadUser(ctx, query, nodes, nil,
			func(n *HusSession, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (hsq *HusSessionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*HusSession, init func(*HusSession), assign func(*HusSession, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*HusSession)
	for i := range nodes {
		fk := nodes[i].UID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "uid" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (hsq *HusSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hsq.querySpec()
	_spec.Node.Columns = hsq.ctx.Fields
	if len(hsq.ctx.Fields) > 0 {
		_spec.Unique = hsq.ctx.Unique != nil && *hsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hsq.driver, _spec)
}

func (hsq *HusSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hussession.Table, hussession.Columns, sqlgraph.NewFieldSpec(hussession.FieldID, field.TypeUUID))
	_spec.From = hsq.sql
	if unique := hsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hsq.path != nil {
		_spec.Unique = true
	}
	if fields := hsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hussession.FieldID)
		for i := range fields {
			if fields[i] != hussession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hsq *HusSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hsq.driver.Dialect())
	t1 := builder.Table(hussession.Table)
	columns := hsq.ctx.Fields
	if len(columns) == 0 {
		columns = hussession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hsq.sql != nil {
		selector = hsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hsq.ctx.Unique != nil && *hsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hsq.predicates {
		p(selector)
	}
	for _, p := range hsq.order {
		p(selector)
	}
	if offset := hsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HusSessionGroupBy is the group-by builder for HusSession entities.
type HusSessionGroupBy struct {
	selector
	build *HusSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hsgb *HusSessionGroupBy) Aggregate(fns ...AggregateFunc) *HusSessionGroupBy {
	hsgb.fns = append(hsgb.fns, fns...)
	return hsgb
}

// Scan applies the selector query and scans the result into the given value.
func (hsgb *HusSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hsgb.build.ctx, "GroupBy")
	if err := hsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HusSessionQuery, *HusSessionGroupBy](ctx, hsgb.build, hsgb, hsgb.build.inters, v)
}

func (hsgb *HusSessionGroupBy) sqlScan(ctx context.Context, root *HusSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hsgb.fns))
	for _, fn := range hsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hsgb.flds)+len(hsgb.fns))
		for _, f := range *hsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HusSessionSelect is the builder for selecting fields of HusSession entities.
type HusSessionSelect struct {
	*HusSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hss *HusSessionSelect) Aggregate(fns ...AggregateFunc) *HusSessionSelect {
	hss.fns = append(hss.fns, fns...)
	return hss
}

// Scan applies the selector query and scans the result into the given value.
func (hss *HusSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hss.ctx, "Select")
	if err := hss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HusSessionQuery, *HusSessionSelect](ctx, hss.HusSessionQuery, hss, hss.inters, v)
}

func (hss *HusSessionSelect) sqlScan(ctx context.Context, root *HusSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hss.fns))
	for _, fn := range hss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
