// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hus-auth/ent/service"
	"hus-auth/ent/subdomain"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubdomainCreate is the builder for creating a Subdomain entity.
type SubdomainCreate struct {
	config
	mutation *SubdomainMutation
	hooks    []Hook
}

// SetServiceID sets the "service_id" field.
func (sc *SubdomainCreate) SetServiceID(i int) *SubdomainCreate {
	sc.mutation.SetServiceID(i)
	return sc
}

// SetSubdomain sets the "subdomain" field.
func (sc *SubdomainCreate) SetSubdomain(s string) *SubdomainCreate {
	sc.mutation.SetSubdomain(s)
	return sc
}

// SetRole sets the "role" field.
func (sc *SubdomainCreate) SetRole(s string) *SubdomainCreate {
	sc.mutation.SetRole(s)
	return sc
}

// SetService sets the "service" edge to the Service entity.
func (sc *SubdomainCreate) SetService(s *Service) *SubdomainCreate {
	return sc.SetServiceID(s.ID)
}

// Mutation returns the SubdomainMutation object of the builder.
func (sc *SubdomainCreate) Mutation() *SubdomainMutation {
	return sc.mutation
}

// Save creates the Subdomain in the database.
func (sc *SubdomainCreate) Save(ctx context.Context) (*Subdomain, error) {
	return withHooks[*Subdomain, SubdomainMutation](ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SubdomainCreate) SaveX(ctx context.Context) *Subdomain {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SubdomainCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SubdomainCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SubdomainCreate) check() error {
	if _, ok := sc.mutation.ServiceID(); !ok {
		return &ValidationError{Name: "service_id", err: errors.New(`ent: missing required field "Subdomain.service_id"`)}
	}
	if _, ok := sc.mutation.Subdomain(); !ok {
		return &ValidationError{Name: "subdomain", err: errors.New(`ent: missing required field "Subdomain.subdomain"`)}
	}
	if _, ok := sc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Subdomain.role"`)}
	}
	if _, ok := sc.mutation.ServiceID(); !ok {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required edge "Subdomain.service"`)}
	}
	return nil
}

func (sc *SubdomainCreate) sqlSave(ctx context.Context) (*Subdomain, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SubdomainCreate) createSpec() (*Subdomain, *sqlgraph.CreateSpec) {
	var (
		_node = &Subdomain{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(subdomain.Table, sqlgraph.NewFieldSpec(subdomain.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.Subdomain(); ok {
		_spec.SetField(subdomain.FieldSubdomain, field.TypeString, value)
		_node.Subdomain = value
	}
	if value, ok := sc.mutation.Role(); ok {
		_spec.SetField(subdomain.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if nodes := sc.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subdomain.ServiceTable,
			Columns: []string{subdomain.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: service.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ServiceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubdomainCreateBulk is the builder for creating many Subdomain entities in bulk.
type SubdomainCreateBulk struct {
	config
	builders []*SubdomainCreate
}

// Save creates the Subdomain entities in the database.
func (scb *SubdomainCreateBulk) Save(ctx context.Context) ([]*Subdomain, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Subdomain, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubdomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SubdomainCreateBulk) SaveX(ctx context.Context) []*Subdomain {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SubdomainCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SubdomainCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
