// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hus-auth/ent/predicate"
	"hus-auth/ent/service"
	"hus-auth/ent/subdomain"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubdomainQuery is the builder for querying Subdomain entities.
type SubdomainQuery struct {
	config
	ctx         *QueryContext
	order       []OrderFunc
	inters      []Interceptor
	predicates  []predicate.Subdomain
	withService *ServiceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubdomainQuery builder.
func (sq *SubdomainQuery) Where(ps ...predicate.Subdomain) *SubdomainQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SubdomainQuery) Limit(limit int) *SubdomainQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SubdomainQuery) Offset(offset int) *SubdomainQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SubdomainQuery) Unique(unique bool) *SubdomainQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SubdomainQuery) Order(o ...OrderFunc) *SubdomainQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryService chains the current query on the "service" edge.
func (sq *SubdomainQuery) QueryService() *ServiceQuery {
	query := (&ServiceClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subdomain.Table, subdomain.FieldID, selector),
			sqlgraph.To(service.Table, service.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subdomain.ServiceTable, subdomain.ServiceColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Subdomain entity from the query.
// Returns a *NotFoundError when no Subdomain was found.
func (sq *SubdomainQuery) First(ctx context.Context) (*Subdomain, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subdomain.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SubdomainQuery) FirstX(ctx context.Context) *Subdomain {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Subdomain ID from the query.
// Returns a *NotFoundError when no Subdomain ID was found.
func (sq *SubdomainQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subdomain.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SubdomainQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Subdomain entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Subdomain entity is found.
// Returns a *NotFoundError when no Subdomain entities are found.
func (sq *SubdomainQuery) Only(ctx context.Context) (*Subdomain, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subdomain.Label}
	default:
		return nil, &NotSingularError{subdomain.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SubdomainQuery) OnlyX(ctx context.Context) *Subdomain {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Subdomain ID in the query.
// Returns a *NotSingularError when more than one Subdomain ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SubdomainQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subdomain.Label}
	default:
		err = &NotSingularError{subdomain.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SubdomainQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Subdomains.
func (sq *SubdomainQuery) All(ctx context.Context) ([]*Subdomain, error) {
	ctx = setContextOp(ctx, sq.ctx, "All")
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Subdomain, *SubdomainQuery]()
	return withInterceptors[[]*Subdomain](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SubdomainQuery) AllX(ctx context.Context) []*Subdomain {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Subdomain IDs.
func (sq *SubdomainQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, "IDs")
	if err = sq.Select(subdomain.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SubdomainQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SubdomainQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, "Count")
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SubdomainQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SubdomainQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SubdomainQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, "Exist")
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SubdomainQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubdomainQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SubdomainQuery) Clone() *SubdomainQuery {
	if sq == nil {
		return nil
	}
	return &SubdomainQuery{
		config:      sq.config,
		ctx:         sq.ctx.Clone(),
		order:       append([]OrderFunc{}, sq.order...),
		inters:      append([]Interceptor{}, sq.inters...),
		predicates:  append([]predicate.Subdomain{}, sq.predicates...),
		withService: sq.withService.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithService tells the query-builder to eager-load the nodes that are connected to
// the "service" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SubdomainQuery) WithService(opts ...func(*ServiceQuery)) *SubdomainQuery {
	query := (&ServiceClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withService = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ServiceID int `json:"service_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Subdomain.Query().
//		GroupBy(subdomain.FieldServiceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SubdomainQuery) GroupBy(field string, fields ...string) *SubdomainGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubdomainGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = subdomain.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ServiceID int `json:"service_id,omitempty"`
//	}
//
//	client.Subdomain.Query().
//		Select(subdomain.FieldServiceID).
//		Scan(ctx, &v)
func (sq *SubdomainQuery) Select(fields ...string) *SubdomainSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SubdomainSelect{SubdomainQuery: sq}
	sbuild.label = subdomain.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubdomainSelect configured with the given aggregations.
func (sq *SubdomainQuery) Aggregate(fns ...AggregateFunc) *SubdomainSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SubdomainQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !subdomain.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SubdomainQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Subdomain, error) {
	var (
		nodes       = []*Subdomain{}
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withService != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Subdomain).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Subdomain{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withService; query != nil {
		if err := sq.loadService(ctx, query, nodes, nil,
			func(n *Subdomain, e *Service) { n.Edges.Service = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SubdomainQuery) loadService(ctx context.Context, query *ServiceQuery, nodes []*Subdomain, init func(*Subdomain), assign func(*Subdomain, *Service)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Subdomain)
	for i := range nodes {
		fk := nodes[i].ServiceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(service.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "service_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sq *SubdomainQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SubdomainQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subdomain.Table, subdomain.Columns, sqlgraph.NewFieldSpec(subdomain.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subdomain.FieldID)
		for i := range fields {
			if fields[i] != subdomain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SubdomainQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(subdomain.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = subdomain.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SubdomainGroupBy is the group-by builder for Subdomain entities.
type SubdomainGroupBy struct {
	selector
	build *SubdomainQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SubdomainGroupBy) Aggregate(fns ...AggregateFunc) *SubdomainGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SubdomainGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, "GroupBy")
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubdomainQuery, *SubdomainGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SubdomainGroupBy) sqlScan(ctx context.Context, root *SubdomainQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubdomainSelect is the builder for selecting fields of Subdomain entities.
type SubdomainSelect struct {
	*SubdomainQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SubdomainSelect) Aggregate(fns ...AggregateFunc) *SubdomainSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SubdomainSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, "Select")
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubdomainQuery, *SubdomainSelect](ctx, ss.SubdomainQuery, ss, ss.inters, v)
}

func (ss *SubdomainSelect) sqlScan(ctx context.Context, root *SubdomainQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
