// Code generated by ent, DO NOT EDIT.

package connectedsessions

const (
	// Label holds the string label denoting the connectedsessions type in the database.
	Label = "connected_sessions"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHsid holds the string denoting the hsid field in the database.
	FieldHsid = "hsid"
	// FieldCsid holds the string denoting the csid field in the database.
	FieldCsid = "csid"
	// Table holds the table name of the connectedsessions in the database.
	Table = "connected_sessions"
)

// Columns holds all SQL columns for connectedsessions fields.
var Columns = []string{
	FieldID,
	FieldHsid,
	FieldCsid,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
