// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"hus-auth/ent/hussession"
	"hus-auth/ent/user"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// HusSession is the model entity for the HusSession schema.
type HusSession struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ExpiredAt holds the value of the "expired_at" field.
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HusSessionQuery when eager-loading is set.
	Edges   HusSessionEdges `json:"edges"`
	user_id *uuid.UUID
}

// HusSessionEdges holds the relations/edges for other nodes in the graph.
type HusSessionEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HusSessionEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HusSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hussession.FieldExpiredAt, hussession.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case hussession.FieldID:
			values[i] = new(uuid.UUID)
		case hussession.ForeignKeys[0]: // user_id
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			return nil, fmt.Errorf("unexpected column %q for type HusSession", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HusSession fields.
func (hs *HusSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hussession.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				hs.ID = *value
			}
		case hussession.FieldExpiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expired_at", values[i])
			} else if value.Valid {
				hs.ExpiredAt = new(time.Time)
				*hs.ExpiredAt = value.Time
			}
		case hussession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				hs.CreatedAt = value.Time
			}
		case hussession.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				hs.user_id = new(uuid.UUID)
				*hs.user_id = *value.S.(*uuid.UUID)
			}
		}
	}
	return nil
}

// QueryOwner queries the "owner" edge of the HusSession entity.
func (hs *HusSession) QueryOwner() *UserQuery {
	return NewHusSessionClient(hs.config).QueryOwner(hs)
}

// Update returns a builder for updating this HusSession.
// Note that you need to call HusSession.Unwrap() before calling this method if this HusSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (hs *HusSession) Update() *HusSessionUpdateOne {
	return NewHusSessionClient(hs.config).UpdateOne(hs)
}

// Unwrap unwraps the HusSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (hs *HusSession) Unwrap() *HusSession {
	_tx, ok := hs.config.driver.(*txDriver)
	if !ok {
		panic("ent: HusSession is not a transactional entity")
	}
	hs.config.driver = _tx.drv
	return hs
}

// String implements the fmt.Stringer.
func (hs *HusSession) String() string {
	var builder strings.Builder
	builder.WriteString("HusSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", hs.ID))
	if v := hs.ExpiredAt; v != nil {
		builder.WriteString("expired_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(hs.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// HusSessions is a parsable slice of HusSession.
type HusSessions []*HusSession
