// Code generated by ent, DO NOT EDIT.

package ent

import (
	"hus-auth/ent/hussession"
	"hus-auth/ent/schema"
	"hus-auth/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hussessionFields := schema.HusSession{}.Fields()
	_ = hussessionFields
	// hussessionDescIat is the schema descriptor for iat field.
	hussessionDescIat := hussessionFields[1].Descriptor()
	// hussession.DefaultIat holds the default value on creation for the iat field.
	hussession.DefaultIat = hussessionDescIat.Default.(func() time.Time)
	// hussessionDescID is the schema descriptor for id field.
	hussessionDescID := hussessionFields[0].Descriptor()
	// hussession.DefaultID holds the default value on creation for the id field.
	hussession.DefaultID = hussessionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[11].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
