// Code generated by ent, DO NOT EDIT.

package ent

import (
	"hus-auth/ent/community"
	"hus-auth/ent/hussession"
	"hus-auth/ent/refreshtoken"
	"hus-auth/ent/schema"
	"hus-auth/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	communityFields := schema.Community{}.Fields()
	_ = communityFields
	// communityDescName is the schema descriptor for name field.
	communityDescName := communityFields[1].Descriptor()
	// community.NameValidator is a validator for the "name" field. It is called by the builders before save.
	community.NameValidator = communityDescName.Validators[0].(func(string) error)
	// communityDescUpdatedAt is the schema descriptor for updated_at field.
	communityDescUpdatedAt := communityFields[2].Descriptor()
	// community.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	community.DefaultUpdatedAt = communityDescUpdatedAt.Default.(func() time.Time)
	// community.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	community.UpdateDefaultUpdatedAt = communityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// communityDescID is the schema descriptor for id field.
	communityDescID := communityFields[0].Descriptor()
	// community.DefaultID holds the default value on creation for the id field.
	community.DefaultID = communityDescID.Default.(func() uuid.UUID)
	hussessionFields := schema.HusSession{}.Fields()
	_ = hussessionFields
	// hussessionDescCreatedAt is the schema descriptor for created_at field.
	hussessionDescCreatedAt := hussessionFields[2].Descriptor()
	// hussession.DefaultCreatedAt holds the default value on creation for the created_at field.
	hussession.DefaultCreatedAt = hussessionDescCreatedAt.Default.(func() time.Time)
	// hussessionDescID is the schema descriptor for id field.
	hussessionDescID := hussessionFields[0].Descriptor()
	// hussession.DefaultID holds the default value on creation for the id field.
	hussession.DefaultID = hussessionDescID.Default.(func() uuid.UUID)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescRevoked is the schema descriptor for revoked field.
	refreshtokenDescRevoked := refreshtokenFields[2].Descriptor()
	// refreshtoken.DefaultRevoked holds the default value on creation for the revoked field.
	refreshtoken.DefaultRevoked = refreshtokenDescRevoked.Default.(bool)
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[3].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	// refreshtokenDescUpdatedAt is the schema descriptor for updated_at field.
	refreshtokenDescUpdatedAt := refreshtokenFields[4].Descriptor()
	// refreshtoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	refreshtoken.DefaultUpdatedAt = refreshtokenDescUpdatedAt.Default.(func() time.Time)
	// refreshtoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	refreshtoken.UpdateDefaultUpdatedAt = refreshtokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// refreshtokenDescID is the schema descriptor for id field.
	refreshtokenDescID := refreshtokenFields[0].Descriptor()
	// refreshtoken.DefaultID holds the default value on creation for the id field.
	refreshtoken.DefaultID = refreshtokenDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
