basePath: /auth
host: lifthus.com
info:
  contact:
    email: lifthus531@gmail.com
    name: API Support
    url: lifthus531@gmail.com
  description: This is Project-Hus's root authentication server containing each user's
    UUID, which is unique for all hus services.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Project-Hus auth server
  version: 0.0.0
paths:
  /auth/google:
    post:
      consumes:
      - application/json
      description: validates the google ID token and redirects with hus refresh token
        to /auth/{token_string}.
      parameters:
      - description: Google ID token
        in: body
        name: jwt
        required: true
        schema:
          type: string
      responses:
        "301":
          description: to /auth/{token_string}
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: processes google auth and redirect with refresh token in url.
      tags:
      - auth
swagger: "2.0"
