// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Community is the predicate function for community builders.
type Community func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
